name: Deploy to HostGator

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run build
        run: npm run build

      - name: Upload to HostGator
        run: |
          echo "HostGator username: $geisian.hreis@gmail.com"
          echo "HostGator password: $"
          rsync -avz dist/ hostgator:/home3/igrej478/repositories/123
